# -*- coding: utf-8 -*-
"""Tuple_&_Sets_DAY-5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E2ls85j8SdjlRlYzpfMvUeukxr5seHiE

# Tuple

## Today we're learning two more Python data structures, but we're keeping it project-based.

### Exercise-1
Creat a Tuple whose output should look like this . Make sure to print values seperately.
Your name
Your age
Your course
"""

info = ("Jaymin",21,"Ai/Ml")
print("Your Name =",info[0])
print("Your Age =",info[1])
print("Your Course =",info[2])
info[0]

"""### Exercise - 2
Tuple unpacking
"""

name , age, course = ("Jaymin",21,"Ai/Ml")
print("Your Name =",name)
print("Your Age =",age)
print("Your Course =",course)

"""# Sets
A set automatically keeps only <b>unique values</b>.
"""

subjects = {"Python", "Math", "Python", "Physics", "Math"}
print(subjects)

"""## Exercise - 1
Creat a new set and a new value in that set.
"""

subjects = {"Python", "Math", "Physics"}
print(subjects)
subjects.add("Ai")
print(subjects)

"""## Exercise - 2
Remove a exsisting value from a set.
"""

subjects = {"Python", "Math", "Physics", "Ai"}
subjects.remove("Math")
print(subjects)

"""## Exercis - 3
<b>in</b> with sets. check if the valuse is present in the Set or not .

"""

subjects = {"Python", "Math", "Physics", "Ai"}
if ("Python") in subjects:
    print("Python is present")
else:
    print("Python is not present")

"""## Exercis - 4
Set operations

### Intersection operation in set
The Intersection() will get the common element between two sets.
"""

python_students = {"Jaymin", "Rahul", "Aman", "Priya"}
ml_students = {"Jaymin", "Aman", "Riya", "Karan"}
same_student = python_students.intersection(ml_students)
print(same_student)

"""### Union( ) operation in set
The Union() operation will get all the elements uniquily of both sets.
"""

python_students = {"Jaymin", "Rahul", "Aman", "Priya"}
ml_students = {"Jaymin", "Aman", "Riya", "Karan"}

all_student = python_students.union(ml_students)
print(all_student)

"""### Difference() operation in set.
the Difference() operation will get on the element that are not common between two sets.
"""

python_students = {"Jaymin", "Rahul", "Aman", "Priya"}
ml_students = {"Jaymin", "Aman", "Riya", "Karan"}

python_only = python_students.difference(ml_students)
print(python_only)

"""## Exercis - 5
# <b>mini-challenge</b>
Let's combine dictionary + set
"""

student = {
    "python_students" : {"Jaymin", "Rahul", "Aman", "Priya"},
    "ml_students" : {"Jaymin", "Aman", "Riya", "Karan"}
}

test = student["python_students"].intersection(student["ml_students"])
print(test)

"""# <b>Final Challenge</b>
Build a small course enrollment analyzer.

Find and print:
Students taking both Python and ML
Students taking Python but not ML
All unique students across all three courses

Use only the concepts you've learned today: dictionary access + sets + intersection() + difference() + union().
"""

courses = {
    "Python": {"Jaymin", "Rahul", "Aman", "Priya"},
    "ML": {"Jaymin", "Aman", "Riya"},
    "Web": {"Rahul", "Priya", "Karan"}
}
intersection_students = courses["Python"].intersection(courses["ML"])
print("Students taking both Python and ML are",intersection_students)
python_only = courses["Python"].difference(courses["ML"])
print("Students taking Python but not ML are",python_only)
unique_students = courses["Python"].union(courses["ML"], courses["Web"])
print("All unique students across all three courses are",unique_students)